spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiangGengGuang/springcloud-config
          search-paths: config-files
server:
  port: 8051
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/